# Generated by Django 5.0.6 on 2024-05-15 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HousePrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg_area_income', models.FloatField()),
                ('avg_house_age', models.FloatField()),
                ('avg_area_rooms', models.FloatField()),
                ('avg_area_bedrooms', models.FloatField()),
                ('avg_area_population', models.FloatField()),
                ('predicted_price', models.FloatField()),
            ],
        ),
    ]
